[package]
name = "vi5-cef"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
cef = { version = "143.7.1", features = ["accelerated_osr"] }
image = "0.25.9"
log = "0.4.29"
pollster = "0.4.0"
rand = "0.9.2"
wgpu = "28"
env_logger = "0.11.8"
